Repository DTStack/molecule, pull requests merged in 2021-12, with the labels that each got.

#552 docs: update the introduction in README
  README.md
Labels: documentation

#557 fix: re-layout the Workbench when StatusBar is hidden
  src/controller/menuBar.ts
  src/workbench/style.scss
  src/workbench/workbench.tsx
Labels: bug

#559 docs: add Google Analytics 4 to website
  website/docusaurus.config.js
  website/package.json
  website/yarn.lock
Labels: documentation

#558 fix: language pack code unification
  src/extensions/locales-defaults/index.ts
  src/extensions/locales-defaults/locales/en.json
  src/extensions/locales-defaults/locales/ko-KR.json
  src/extensions/locales-defaults/locales/zh-CN.json
  src/i18n/__tests__/localeService.test.ts
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
Labels: enhancement

#564 feat: use css to control the display and hiding of modules under workbench
  src/components/display/__tests__/__snapshots__/display.test.tsx.snap
  src/components/display/__tests__/display.test.tsx
  src/components/display/index.tsx
  src/components/index.ts
  src/controller/__tests__/activityBar.test.ts
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
  src/workbench/__tests__/__snapshots__/workbench.test.tsx.snap
  src/workbench/__tests__/workbench.test.tsx
  src/workbench/menuBar/style.scss
  src/workbench/style.scss
  src/workbench/workbench.tsx
Labels: enhancement

#569 docs: update relevant documents of MenuBar
  website/docs/advanced/customize-workbench.md
  website/docs/guides/extend-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/customize-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-workbench.md
Labels: documentation

#573 chore: update issue templates
  .github/ISSUE_TEMPLATE/bug_report.md
  .github/ISSUE_TEMPLATE/feature_request.md
  .github/ISSUE_TEMPLATE/question.md
Labels: enhancement

#574 docs: update docs url to relative path
  website/docs/advanced/customize-workbench.md
  website/docs/guides/extend-builtin-ui.md
  website/docs/guides/extend-color-theme.md
  website/docs/guides/extend-keybinding.md
  website/docs/guides/extend-locales.md
  website/docs/guides/extend-quick-access.md
  website/docs/guides/extend-settings.md
  website/docs/guides/extend-workbench.md
  website/docs/guides/extension.md
  website/docs/guides/icons.md
  website/docs/overview.md
  website/docs/the-first-extension.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/customize-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-color-theme.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-keybinding.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-locales.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-quick-access.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-settings.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extension.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/icons.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/overview.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/the-first-extension.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/advanced/customize-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-color-theme.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-keybinding.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-locales.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-quick-access.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-settings.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extension.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/icons.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/overview.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/the-first-extension.md
  website/versioned_docs/version-0.9.0-beta.1/advanced/customize-workbench.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-builtin-ui.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-color-theme.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-keybinding.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-locales.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-quick-access.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-settings.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-workbench.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extension.md
  website/versioned_docs/version-0.9.0-beta.1/guides/icons.md
  website/versioned_docs/version-0.9.0-beta.1/overview.md
  website/versioned_docs/version-0.9.0-beta.1/the-first-extension.md
Labels: documentation

#568 docs: add korean README and add test method
  README-koKR.md
  README-zhCN.md
  README.md
Labels: documentation

#575 docs: add code of conduct
  CODE_OF_CONDUCT.md
Labels: documentation

#578 fix: correct the style of input and select
  src/components/input/style.scss
  src/components/select/style.scss
  src/workbench/sidebar/explore/style.scss
  src/workbench/style.scss
Labels: bug

#567 feat: provide types of Keybinding and QuickAccess
  src/model/index.ts
  src/molecule.api.ts
  src/monaco/api.ts
  src/monaco/index.ts
  website/sidebars.js
Labels: enhancement
