Repository DTStack/molecule, pull requests merged in 2022-10, with the labels that each got.

#815 fix: improve breadcrumb
  src/components/breadcrumb/style.scss
Labels: bug

#807 feat: support stop event emit
  src/common/event/__tests__/eventEmitter.test.ts
  src/common/event/eventEmitter.ts
  website/docs/advanced/event.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/event.md
Labels: enhancement

#810 refactor: optimize modal confirm button style and fix redundacy heade…
  src/components/dialog/__tests__/__snapshots__/actionbutton.test.tsx.snap
  src/components/dialog/__tests__/actionbutton.test.tsx
  src/components/dialog/__tests__/confirm.test.tsx
  src/components/dialog/actionButton.tsx
  src/components/dialog/confirm.tsx
  src/components/dialog/confirmDialog.tsx
  src/components/dialog/modal.tsx
  src/components/dialog/style.scss
  stories/components/17-Dialog.stories.tsx
Labels: bug, enhancement
