Repository DTStack/molecule, pull requests merged in 2022-02, with the labels that each got.

#643 feat: LocaleNotification supports to trigger reload by pressing the Enter key
  src/workbench/notification/__tests__/__snapshots__/localeNotification.test.tsx.snap
  src/workbench/notification/__tests__/localeNotification.test.tsx
  src/workbench/notification/notificationPane/localeNotification.tsx
Labels: feature

#647 fix: the interaction bug of MenuBar in horizontal mode
  src/workbench/menuBar/__tests__/menubar.test.tsx
  src/workbench/menuBar/horizontalView.tsx
Labels: bug

#651 fix: the context menu does not close when the context menu item is clicked.
  src/components/menu/menu.tsx
Labels: bug

#652 fix: update explorer when closing editor tab
  src/services/workbench/editorService.ts
Labels: bug

#654 fix: improve the style of the Button in Notification
  src/workbench/notification/style.scss
Labels: bug

#656 fix: add icons to EditorTree and optimize its style
  src/workbench/sidebar/explore/editorTree.tsx
  src/workbench/sidebar/explore/style.scss
Labels: bug

#650 fix: customized MenuBar data will be lost when modifying the MenuBar's mode
  src/controller/__tests__/menuBar.test.ts
  src/controller/menuBar.ts
  src/model/workbench/menuBar.ts
  src/services/builtinService/const.ts
Labels: bug

#657 fix: improve the style of the EditorTree node's icon
  src/workbench/sidebar/explore/style.scss
Labels: bug

#659 fix: filename missing and file path in EditorTree is not updated
  src/extensions/__tests__/folderTree.test.tsx
  src/extensions/folderTree/index.tsx
  src/model/workbench/editor.ts
Labels: bug

#661 ci: add action for github page deployment
  .github/workflows/deploy.yml
  .github/workflows/test-deploy.yml
  package.json
Labels: build

#665 fix: improve the style of scrollbar in Scrollable component
  src/components/scrollable/style.scss
  src/workbench/editor/welcome/style.scss
Labels: bug

#509 feat: develop a Split Pane component
  src/components/collapse/__tests__/__snapshots__/index.test.tsx.snap
  src/components/collapse/__tests__/index.test.tsx
  src/components/collapse/base.tsx
  src/components/collapse/index.tsx
  src/components/collapse/style.scss
  src/components/index.ts
  src/components/split/SplitPane.tsx
  src/components/split/__tests__/__snapshots__/index.test.tsx.snap
  src/components/split/__tests__/index.test.tsx
  src/components/split/base.ts
  src/components/split/index.ts
  src/components/split/pane.tsx
  src/components/split/sash.tsx
  src/components/split/style.scss
  src/controller/__tests__/layout.test.ts
  src/controller/editor.tsx
  src/controller/layout.ts
  src/extensions/theme-defaults/themes/dark_defaults.json
  src/extensions/theme-defaults/themes/hc_black_defaults.json
  src/extensions/theme-defaults/themes/light_defaults.json
  src/model/workbench/layout.ts
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
  src/provider/__tests__/molecule.test.tsx
  src/services/theme/colorRegistry.ts
  src/services/theme/helper.ts
  src/services/workbench/editorService.ts
  src/services/workbench/layoutService.ts
  src/style/common.scss
  src/style/mo.scss
  src/workbench/__tests__/__snapshots__/workbench.test.tsx.snap
  src/workbench/__tests__/workbench.test.tsx
  src/workbench/editor/__tests__/__snapshots__/editor.test.tsx.snap
  src/workbench/editor/__tests__/editor.test.tsx
  src/workbench/editor/editor.tsx
  src/workbench/editor/index.tsx
  src/workbench/sidebar/__tests__/__snapshots__/explore.test.tsx.snap
  src/workbench/sidebar/__tests__/__snapshots__/siderbar.test.tsx.snap
  src/workbench/sidebar/sidebar.tsx
  src/workbench/sidebar/style.scss
  src/workbench/workbench.tsx
  stories/components/19-Split.stories.tsx
  test/setupTests.tsx
Labels: feature

#664 feat: support to set the expandKeys
  src/components/tree/index.tsx
  src/controller/__tests__/folderTree.test.ts
  src/controller/explorer/folderTree.tsx
  src/extensions/folderTree/index.tsx
  src/model/workbench/explorer/folderTree.tsx
  src/services/workbench/__tests__/folderTreeService.test.ts
  src/services/workbench/explorer/folderTreeService.ts
  src/workbench/sidebar/explore/folderTree.tsx
Labels: feature

#668 refactor: replace the A tag by button tag in Button component
  src/components/button/__tests__/__snapshots__/button.test.tsx.snap
  src/components/button/index.tsx
  src/components/button/style.scss
  src/components/dialog/__tests__/__snapshots__/actionbutton.test.tsx.snap
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
  src/services/theme/colorRegistry.ts
  src/services/theme/helper.ts
  src/workbench/notification/__tests__/__snapshots__/localeNotification.test.tsx.snap
  src/workbench/sidebar/__tests__/folderTree.test.tsx
  stories/components/17-Dialog.stories.tsx
Labels: refactoring

#669 feat: Improve usage examples in TestPane
  stories/extensions/test/testPane.tsx
Labels: enhancement

#670 fix: prevent the contextmenu event of Notification
  src/controller/notification.tsx
  src/workbench/notification/__tests__/notificationPane.test.tsx
  src/workbench/notification/notificationPane/index.tsx
Labels: bug
