Repository DTStack/molecule, pull requests merged in 2022-05, with the labels that each got.

#735 fix: throws the full Error message when the Extension load exception
  src/services/extensionService.ts
Labels: bug, feature

#736 fix(editor): fix styles in editor tab extra
  src/components/tabs/__tests__/__snapshots__/tabs.test.tsx.snap
  src/components/tabs/__tests__/tabExtra.test.tsx
  src/components/tabs/__tests__/tabs.test.tsx
  src/components/tabs/style.scss
  src/components/tabs/tab.tsx
  src/components/tabs/tabExtra.tsx
  stories/extensions/test/testPane.tsx
Labels: bug

#740 fix(components): add color variables for breadcrumb
  src/components/breadcrumb/__tests__/__snapshots__/breadcrumb.test.tsx.snap
  src/components/breadcrumb/__tests__/breadcrumb.test.tsx
  src/components/breadcrumb/index.tsx
  src/components/breadcrumb/style.scss
Labels: bug

#746 fix: use the enter character \u21a9
  src/model/keybinding.ts
Labels: bug

#750 fix: update tab set value
  src/controller/editor.tsx
  src/services/workbench/__tests__/editorService.test.tsx
  src/services/workbench/editorService.ts
Labels: bug

#752 feat: add getParentNode interface for folderTreeService
  src/services/workbench/__tests__/folderTreeService.test.ts
  src/services/workbench/explorer/folderTreeService.ts
  stories/extensions/test/testPane.tsx
Labels: feature
