Repository DTStack/molecule, pull requests merged in 2022-01, with the labels that each got.

#584 docs: translate extend-workbench
  website/docs/guides/extend-workbench.md
Labels: documentation

#592 docs: translate Overview, QuickStart to English
  website/docs/overview.md
  website/docs/quick-start.md
  website/docs/the-first-extension.md
Labels: documentation

#581 docs: translate the docs in English
  website/docs/advanced/customize-workbench.md
  website/docs/guides/extend-builtin-ui.md
  website/docs/guides/extend-color-theme.md
  website/docs/guides/extend-keybinding.md
  website/docs/guides/extend-locales.md
  website/docs/guides/extend-quick-access.md
  website/docs/guides/extend-settings.md
  website/docs/guides/extend-workbench.md
  website/docs/guides/extension.md
  website/docs/guides/icons.md
  website/docs/overview.md
  website/docs/quick-start.md
  website/docs/the-first-extension.md
Labels: documentation

#597 docs: set the locale as English by default
  website/docusaurus.config.js
Labels: documentation

#600 docs: add Algolia DocSearch to website
  website/docusaurus.config.js
Labels: documentation

#602 docs: add contextualSearch configuration
  website/docusaurus.config.js
Labels: documentation

#608 docs: remove the external properties and methods in API docs
  website/docusaurus.config.js
Labels: documentation

#613 fix: the style of the context menu of ActivityBarItem
  src/common/__tests__/dom.test.ts
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
  src/workbench/activityBar/__tests__/activityBarItem.test.tsx
  src/workbench/activityBar/activityBarItem.tsx
Labels: bug

#599 feat: support to dispose the Action
  codecov.yml
  jest.config.js
  src/controller/extension.ts
  src/i18n/selectLocaleAction.ts
  src/monaco/__tests__/action.test.ts
  src/monaco/action.ts
  src/monaco/api.ts
  src/monaco/common.ts
  src/monaco/index.ts
  src/monaco/quickAccessSettingsAction.ts
  src/monaco/quickAccessViewAction.ts
  src/monaco/quickCopyLineUp.ts
  src/monaco/quickCreateFile.ts
  src/monaco/quickRedo.ts
  src/monaco/quickSelectAllAction.ts
  src/monaco/quickTogglePanelAction.ts
  src/monaco/quickToggleSideBarAction.ts
  src/monaco/quickUndo.ts
  src/monaco/selectColorThemeAction.ts
  src/services/__tests__/extensionService.test.ts
  src/services/extensionService.ts
  stories/extensions/actions/quickOpen.ts
  stories/extensions/data-sync/index.tsx
  stories/extensions/test/index.tsx
Labels: enhancement

#614 feat: support to set the folderTree nodes whether to sort by default
  src/model/workbench/explorer/folderTree.tsx
  src/services/workbench/__tests__/folderTreeService.test.ts
  src/services/workbench/explorer/folderTreeService.ts
  website/docs/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md
Labels: bug

#617 feat: remove the onRemove processing logic in the built-in FolderTree extension
  src/extensions/folderTree/index.tsx
  stories/extensions/test/index.tsx
  website/docs/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md
Labels: refactoring

#618 docs: improve the link about Search Service
  website/docs/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.1/guides/extend-builtin-ui.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/version-0.9.0-beta.2/guides/extend-builtin-ui.md
  website/versioned_docs/version-0.9.0-beta.1/guides/extend-builtin-ui.md
  website/versioned_docs/version-0.9.0-beta.2/guides/extend-builtin-ui.md
Labels: documentation

#628 docs: add the chat entry of Discord
  README-koKR.md
  README-zhCN.md
  README.md
  website/docs/introduction.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
Labels: documentation

#630 Upgrade the react-dnd to latest stable version
  package.json
  src/components/input/__tests__/input.test.tsx
  src/components/tabs/__tests__/tab.test.tsx
  src/components/tabs/dragAndDrop.tsx
  src/components/tabs/index.tsx
  src/components/tabs/tab.tsx
  yarn.lock
Labels: enhancement, dependencies

#637 fix: sync menuBar mode status
  src/controller/menuBar.ts
  src/model/workbench/menuBar.ts
  src/services/workbench/layoutService.ts
  stories/extensions/test/testPane.tsx
Labels: bug

#635 fix: Connect component supports to unsubscribe event by pass the callback
  src/common/event/__tests__/eventEmitter.test.ts
  src/common/event/eventBus.ts
  src/common/event/eventEmitter.ts
  src/components/menu/style.scss
  src/react/__tests__/connector.test.tsx
  src/react/component.ts
  src/react/connector.tsx
  stories/components/17-Dialog.stories.tsx
  stories/extensions/extend-panel/index.tsx
  stories/extensions/extend-panel/pane.tsx
  stories/extensions/index.ts
Labels: bug

#639 fix: let the defaultLocale property of MoleculeProvider work.
  src/i18n/localeService.ts
  src/provider/molecule.tsx
Labels: bug

#642 refactor(connector): filter the useless properties of Controller
  src/controller/__tests__/menuBar.test.ts
  src/controller/menuBar.ts
  src/react/connector.tsx
Labels: refactoring

#641 feat: support to get the mode(dark or light) of the current color theme
  src/common/__tests__/utils.test.ts
  src/common/utils.ts
  src/model/colorTheme.ts
  src/services/__tests__/colorThemeService.test.ts
  src/services/theme/colorThemeService.ts
Labels: feature
