Repository DTStack/molecule, pull requests merged in 2022-06, with the labels that each got.

#753 support to set the expanded panels of Explorer
  src/components/collapse/__tests__/index.test.tsx
  src/components/collapse/index.tsx
  src/model/workbench/explorer/explorer.tsx
  src/services/__tests__/explorerService.test.ts
  src/services/workbench/explorer/explorerService.ts
  src/workbench/sidebar/explore/explore.tsx
  stories/extensions/test/testPane.tsx
Labels: feature

#759 feat:Exposing more props to renderPane for EditorTab
  src/components/tabs/tab.tsx
  src/workbench/editor/__tests__/group.test.tsx
  src/workbench/editor/editor.tsx
  src/workbench/editor/group.tsx
  stories/extensions/test/testPane.tsx
Labels: feature

#762 docs: add the DingTalk in README
  README-zhCN.md
  README.md
  website/docs/introduction.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/introduction.md
  website/static/img/qrcode-chat.jpg
Labels: documentation

#763 refactor: refactor Split component
  src/components/collapse/__tests__/__snapshots__/index.test.tsx.snap
  src/components/collapse/__tests__/index.test.tsx
  src/components/collapse/index.tsx
  src/components/split/SplitPane.tsx
  src/components/split/__tests__/__snapshots__/index.test.tsx.snap
  src/components/split/__tests__/index.test.tsx
  src/components/split/base.ts
  src/components/split/sash.tsx
  src/components/split/style.scss
  src/model/workbench/layout.ts
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
  src/workbench/__tests__/__snapshots__/workbench.test.tsx.snap
  src/workbench/__tests__/workbench.test.tsx
  src/workbench/editor/__tests__/__snapshots__/editor.test.tsx.snap
  src/workbench/editor/editor.tsx
  src/workbench/sidebar/__tests__/__snapshots__/explore.test.tsx.snap
  src/workbench/workbench.tsx
  stories/components/19-Split.stories.tsx
Labels: refactoring

#768 fix: prevent multiply calls of render function
  src/services/instanceService.tsx
Labels: bug

#770 ci: add yarn web stage
  .github/workflows/main.yml
  package.json
Labels: build

#771 ci: improve release script
  package.json
  scripts/release.mjs
Labels: build
