Repository DTStack/molecule, pull requests merged in 2022-03, with the labels that each got.

#671 refactor: improve notification
  src/components/button/index.tsx
  src/controller/__tests__/setting.test.ts
  src/controller/settings.tsx
  src/extensions/locales-defaults/locales/en.json
  src/extensions/locales-defaults/locales/zh-CN.json
  src/provider/__tests__/__snapshots__/molecule.test.tsx.snap
  src/style/common.scss
  src/workbench/notification/__tests__/__snapshots__/localeNotification.test.tsx.snap
  src/workbench/notification/__tests__/__snapshots__/notificationPane.test.tsx.snap
  src/workbench/notification/__tests__/__snapshots__/statusBarView.test.tsx.snap
  src/workbench/notification/__tests__/localeNotification.test.tsx
  src/workbench/notification/notificationPane/index.tsx
  src/workbench/notification/notificationPane/localeNotification.tsx
  src/workbench/notification/statusBarView/index.scss
  src/workbench/notification/statusBarView/index.tsx
  src/workbench/notification/style.scss
  src/workbench/statusBar/style.scss
  stories/extensions/test/testPane.tsx
Labels: refactoring

#673 feat: support listen to onCollapseAllFolders
  src/components/tree/index.tsx
  src/controller/__tests__/explorer.test.ts
  src/controller/explorer/explorer.tsx
  src/model/workbench/explorer/explorer.tsx
  src/services/__tests__/explorerService.test.ts
  src/services/builtinService/const.ts
  src/services/workbench/explorer/explorerService.ts
  stories/extensions/test/index.tsx
Labels: feature

#686 fix: make Keybinding work after reloading Molecule
  src/common/__tests__/dom.test.ts
  src/common/__tests__/utils.test.ts
  src/provider/molecule.tsx
  src/services/workbench/layoutService.ts
Labels: bug

#689 fix: move the style of statusBarView into mo.scss
  src/style/mo.scss
  src/workbench/notification/statusBarView/index.tsx
  src/workbench/notification/statusBarView/style.scss
Labels: bug

#692 fix: import Icon, Toolbar from relative path
  src/components/collapse/index.tsx
Labels: bug

#696 fix: enable the editor to save viewState
  src/controller/__tests__/editor.test.ts
  src/controller/editor.tsx
Labels: bug

#698 fix: prevent the editor from initializing when switching tabs
  src/workbench/editor/group.tsx
Labels: bug

#705 docs: update customize workbench
  .github/workflows/deploy.yml
  .github/workflows/test-deploy.yml
  website/docs/advanced/customize-workbench.md
  website/docs/guides/extend-keybinding.md
  website/docs/guides/extend-quick-access.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/advanced/customize-workbench.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-keybinding.md
  website/i18n/zh-CN/docusaurus-plugin-content-docs/current/guides/extend-quick-access.md
Labels: documentation

#711 fix: compatible background color for buttons and menu items
  src/services/theme/helper.ts
Labels: bug

#712 feat: the tree in Problems panel supports onSelect event
  src/controller/__tests__/problems.test.ts
  src/controller/problems.tsx
  src/model/problems.tsx
  src/services/problemsService.ts
  src/workbench/problems/paneView/index.tsx
Labels: feature
