Repository DTStack/molecule, pull requests merged in 2022-07, with the labels that each got.

#773 feat: the text of the optimized tree item is too long
  src/components/tree/style.scss
Labels: bug

#777 fix: remove invalid Regex in Safari
  src/services/workbench/explorer/folderTreeService.ts
Labels: bug

#774 feat: bump react'version to 18.x
  .storybook/main.js
  jest.config.js
  mock/monacoMock.js
  package.json
  src/components/collapse/__tests__/index.test.tsx
  src/components/contextMenu/__tests__/contextMenu.test.tsx
  src/components/contextView/__tests__/contextView.test.tsx
  src/components/contextView/index.tsx
  src/components/dialog/confirm.tsx
  src/components/dropdown/__tests__/dropdown.test.tsx
  src/components/scrollable/__tests__/scrollable.test.tsx
  src/components/scrollable/index.tsx
  src/components/select/__tests__/select.test.tsx
  src/components/tabs/tab.tsx
  src/components/tree/__tests__/tree.test.tsx
  src/extensions/__tests__/folderTree.test.tsx
  src/react/__tests__/connector.test.tsx
  src/react/__tests__/render-react.test.tsx
  src/react/__tests__/render.test.tsx
  src/react/render.ts
  src/services/workbench/__tests__/editorService.test.tsx
  src/services/workbench/__tests__/folderTreeService.test.tsx
  src/workbench/activityBar/__tests__/activityBar.test.tsx
  src/workbench/activityBar/__tests__/activityBarItem.test.tsx
  src/workbench/editor/__tests__/group.test.tsx
  src/workbench/menuBar/__tests__/menubar.test.tsx
  src/workbench/notification/__tests__/__snapshots__/notificationPane.test.tsx.snap
  src/workbench/notification/statusBarView/index.tsx
  src/workbench/sidebar/__tests__/editorTree.test.tsx
  src/workbench/sidebar/__tests__/explore.test.tsx
  stories/components/10-Menu.stories.tsx
  stories/components/11-DownDown.stories.tsx
  stories/components/12-Button.stories.tsx
  stories/components/13-Icon.stories.tsx
  stories/components/14-Scrollable.stories.tsx
  stories/components/15-Input.stories.tsx
  stories/components/15-Select.stories.tsx
  stories/components/16-Checkbox.stories.tsx
  stories/components/17-Dialog.stories.tsx
  stories/components/18-Breadcrumb.stories.tsx
  stories/components/3-Tabs.stories.tsx
  stories/components/4-Tree.stories.tsx
  stories/components/6-ActionBar.stories.tsx
  stories/components/8-ContextView.stories.tsx
  stories/components/9-List.stories.tsx
  yarn.lock
Labels: dependencies

#779 fix: updateTab will change the reference of current tab
  src/services/workbench/editorService.ts
Labels: bug

#778 fix: fix set entry failed at some situations
  src/services/workbench/editorService.ts
Labels: bug

#781 fix: prevent updateTab with renderPanel tab
  src/services/workbench/__tests__/editorService.test.tsx
  src/services/workbench/editorService.ts
Labels: bug

#782 chore: update react version of peerDependencies
  package.json
Labels: dependencies

#783 ci: update release
  scripts/release.mjs
Labels: enhancement
